name: CI for working branch

on: [push]
  
jobs:

  CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./testing

    steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}
    
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

        - uses: hashicorp/setup-terraform@v2

        - name: init
          run: terraform init

        - name: validate
          run: terraform validate

        # - name: Secret Scanner
        #   uses: secret-scanner/action@0.0.2