name: Deploy/Teardown

on:
  workflow_dispatch:
    inputs:
      deployment:
        type: choice
        description: DeployOrTearDown
        options:
          - Setup
          - TearDown

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  deployment:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./testing
        
    steps:
      - uses: actions/checkout@v4
    
      - uses: hashicorp/setup-terraform@v2

      - run: terraform init

      - run: terraform validate

      - run: terraform plan

      - name: Setup or TearDown
        run: |
          if [ ${{ github.event.inputs.deployment }} == 'Setup' ]; then  
            terraform apply -auto-approve
          elif [ ${{ github.event.inputs.deployment }} == 'TearDown' ]; then  
            terraform destroy -auto-approve
          fi
        shell: bash

    #   - name: Push ECR repo name to organization variables
    #     run: |
    #       if [ ${{ github.event.inputs.deployment }} == 'Setup' ]; then  
    #         cat ecr_url.dat
    #         source ecr_url.dat
    #         curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/ECR_URL_PYDBCAPSTONE -d '{"name":"ECR_URL_PYDBCAPSTONE","value":"'$ECR_REPO_URL'","visibility":"all"}'
    #       elif [ ${{ github.event.inputs.deployment }} == 'TearDown' ]; then
    #         curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/ECR_URL_PYDBCAPSTONE -d '{"name":"ECR_URL_PYDBCAPSTONE","value":"DESTROYED","visibility":"all"}'
    #       fi